version: "{branch}-ci-{build}"
image: Visual Studio 2017


environment:
  matrix:
  - build: g++
    platform: x64
    MINGW_ROOT: C:\msys64\mingw64
    BOOST_ROOT: C:\msys64\mingw64\include\boost
    LIBELF_INCLUDE: C:\msys64\mingw64\include\libelf
    MINGW_ARCH: x86_64
    MSYSTEM: MINGW64


install:
  - set PATH=%MINGW_ROOT%;%MINGW_ROOT%\bin;C:\msys64\usr\bin\;"C:\Program Files\LLVM\bin";%PATH%
  - bash -lc "pacman --needed --noconfirm -S mingw-w64-%MINGW_ARCH%-libelf"
  - bash -lc "pacman --needed --noconfirm -S mingw-w64-%MINGW_ARCH%-boost"
  - set CPATH=%LIBELF_INCLUDE%;%CPATH%
  - set CPLUS_INCLUDE_PATH=%LIBELF_INCLUDE%;%BOOST_ROOT%;%CPLUS_INCLUDE_PATH%
  - set BINARY_NAME=dinamo-windows-%platform%.exe


build_script:
  - bash -lc "exec 0</dev/null && cd $APPVEYOR_BUILD_FOLDER && make "
  # - bash -lc "cd $APPVEYOR_BUILD_FOLDER && scripts/run_tests.sh"
  - bash -lc true

artifacts:
  - path: bin\dinamo.exe
    name: Releases

deploy:
  release: DiNAMO-v$(appveyor_build_version)
  description: 'Mac OS X and Windows 64 binaries'
  provider: GitHub
  auth_token:
    secure: 4pbkaIiW4tf9KoszzJw02C1c5Levwbj1F2jmZIARZlmwdI67OSEiJFaQJ1EMHTdQ
  artifact: /dinamo/
  draft: true
  prerelease: true
  on:
    appveyor_repo_tag: false
    platform: x64
