notifications:
    email: false

###############################################

env:
  - secure: "cMkn0Em26i4QGIiJQ4FrvBaRqTe1mqeYAqCawpsjXQg8T3V8O7oDW67ZEq08A8GZlZ8IVUYpXOsOIkKcizWlVwwwIEH0GTxLXVAC3zYOMmVEts+ui58PQnwcZl3goGZ5oQDMFCaGKc84WsQ5qBVrK4OEEVcsw5kwNk3cmgc3nF/H1p7KgUL9sZtGoh6DwN4fLnJgwvYjsx1n/Unc7XuBy6Bb4sW09TOYyLUAlaTiuU3Eee3EZmKadYt1lDrv8d4GkEhBKeD1s9YTAPrC+f2t5PforO9BIVNibgk3PUcKnVyy6h8n2qWh4qHYT9KyFmqCCN2DuoWSXYj0igVxv8AM15Y89rIdJSqzw087PlK4QAI9j54EQCb8VK4p3Jvt1we0S+xxqzkxBOKgxdJx4LMuQz1dYlPoIVfoTHR5fWtgV/XLxXqa5rXOH7Lf9RFdGVI9jpa6nqVEXNAWLvR+b9ywPq59r1glgBXVnJSSMTvwXyfplP+Y+6AEok3vIQywou8bJ1uXzVy5epvNtolagbt74dM5MDcv+zga4/yLNpAZTuYB4u8qov+3ODWoRX+54X/LcheJw6Q+CsxAieJjnPCVDgK6itmzaHzj8wiBzaA01YbRzoLnumKJVzw5qm7MeJ4DWCQHmx+X2B2+rIt7OXlTyw+HexujV00M62FbZIEqV+I="

###############################################

sudo: require
dist: trusty
language: cpp
matrix:
  include:
    
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libboost-math-dev
            - g++-4.9
      env: COMPILER=g++-4.9
    
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libboost-math-dev
            - g++-5
      env: COMPILER=g++-5
    
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - libboost-math-dev
            - clang-3.6
      env: COMPILER=clang++-3.6
    
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - libboost-math-dev
            - clang-3.7
      env: COMPILER=clang++-3.7

    - os: osx
      osx_image: xcode8
      sudo: false



################################################

# making sure we use latest g++
before_script:
  - chmod ugo+x scripts/run_tests.sh

script:
  - export CXX=${COMPILER}
  - make
#  - scripts/run_tests.sh

after_success:
  - chmod ugo+x scripts/travis_auto_merger.sh
  - "BRANCH_TO_MERGE='unstable' BRANCH_TO_MERGE_INTO=master GITHUB_REPO=bonsai-team/DiNAMO scripts/travis_auto_merger.sh"

before_deploy:
  - export FILE_TO_UPLOAD=$(ls bin/dinamo)

deploy:
  provider: releases
  secure: "PsbiJfEY6mPM3B8NuYLfhHaglo7nsU62o2D9zRQkz/di6JgCIEJWBCeCe7XkgAhIHBHolHchE04axrGmIyleaOf8WSCWtMTHfIeAapeI/VGSyNRf/ttV+jWiismN9xMlrx+PKzRphDYSgefWkWAcpYxv9KI0kW2VTpXbsPQJRYJ1k8B3mXpIbegwQFAAz6jvBkCQFX5HcD4fykBwVg29ahoBG2d2xYt2eeeT1OAq3XsaHWvBMquoC/UeWp9u/xWkSFIM9iS1/ef/xS7C7CrMdLxS0XCk0Zcg/FM2ZauyIpQ+/+58iVdUJOl+pQ45CfqDCdELY1ciVXA9zuIibQbHFPPzTpII80/IKa3if+iS+hSnftImuyHyO7rKKpFq6+CGkYYmkTjs4wUeNPQEmZ7c9rDV8nr/UA+z9iifGV3T5K7jzg29GS0yDQzqD0pZFyt8mEEbvhz+Zba/3HJhpF0OBoIgQi0xoNW0QIhlozkC59cCj4k/22iIo1Zteb7AC1cCGix0ZsQKJpWRnsJzk/yuK7hN9U4jWc047lQV2jNuFnvKZ5HxznwRzSbsw8JT3ms+vXf7yYIMseZo80CLPjSjwaftS6Xaa20Jyz2rkkn6EexKbfEm51ih9qMyR5i+9+1xid5dU3Gvu7umvULpq7yCn4ED9qe2Di0N1OfuaQs3DjA="
  file: "${FILE_TO_UPLOAD}"
  skip_cleanup: true
  on:
    tags: false
    all_branches: true
