dist: trusty
sudo: require

language: cpp
compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6

script: make #-j4 && make test -j4

# need to install the Boost libraries to the sandbox
before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install libboost-math-dev

before_script:
  - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
  - g++ -v
  - export CXX=/usr/bin/g++-6
