notifications:
    email: false

###############################################

env:
  - secure: "cMkn0Em26i4QGIiJQ4FrvBaRqTe1mqeYAqCawpsjXQg8T3V8O7oDW67ZEq08A8GZlZ8IVUYpXOsOIkKcizWlVwwwIEH0GTxLXVAC3zYOMmVEts+ui58PQnwcZl3goGZ5oQDMFCaGKc84WsQ5qBVrK4OEEVcsw5kwNk3cmgc3nF/H1p7KgUL9sZtGoh6DwN4fLnJgwvYjsx1n/Unc7XuBy6Bb4sW09TOYyLUAlaTiuU3Eee3EZmKadYt1lDrv8d4GkEhBKeD1s9YTAPrC+f2t5PforO9BIVNibgk3PUcKnVyy6h8n2qWh4qHYT9KyFmqCCN2DuoWSXYj0igVxv8AM15Y89rIdJSqzw087PlK4QAI9j54EQCb8VK4p3Jvt1we0S+xxqzkxBOKgxdJx4LMuQz1dYlPoIVfoTHR5fWtgV/XLxXqa5rXOH7Lf9RFdGVI9jpa6nqVEXNAWLvR+b9ywPq59r1glgBXVnJSSMTvwXyfplP+Y+6AEok3vIQywou8bJ1uXzVy5epvNtolagbt74dM5MDcv+zga4/yLNpAZTuYB4u8qov+3ODWoRX+54X/LcheJw6Q+CsxAieJjnPCVDgK6itmzaHzj8wiBzaA01YbRzoLnumKJVzw5qm7MeJ4DWCQHmx+X2B2+rIt7OXlTyw+HexujV00M62FbZIEqV+I="

###############################################

sudo: require
dist: trusty
language: cpp
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - libboost-math-dev
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - libboost-math-dev
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - libboost-math-dev
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env: COMPILER=clang++-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - libboost-math-dev
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: COMPILER=clang++-3.7

################################################

# making sure we use latest g++
before_script:
  - chmod ugo+x scripts/run_tests.sh

script:
  - ${CXX} -v
  - echo ${COMPILER}
  - which g++-4.9
  - which g++-5
  - which g++
  - make
  - scripts/run_tests.sh

after_success:
#  - chmod ugo+x scripts/travis_auto_merger.sh
#  - "BRANCH_TO_MERGE='unstable' BRANCH_TO_MERGE_INTO=master GITHUB_REPO=bonsai-team/DiNAMO scripts/travis_auto_merger.sh"
